### PR TITLE
Removed Google auth

### PR DESCRIPTION
**Pull request by Tristan-C789**
This PR aims to remove any code related to Google authentication, as it is not needed anymore. 

# Google auth
The removed code includes the associated types, as well as the `signInWithGoogle` function itself.

# Logs
A few logs were added to make development easier down the road.

### CODE REVIEW

**Review by margdsq — APPROVED** [review]
LGTM

**Review by Roman-batut — CHANGES_REQUESTED** [review]
I think you forgot to remove certain mentions and usage of Google auth such as in _sign_up_screen_ where _logInWithGoogle_ is imported.

Also you should rebase and solve the possible merge conflicts that could take place.

**Comment by Tristan-C789** [comment]
The issues that were pointed at were solved indirectly with the merge with master. This PR is ready to go into production!

**Review by Roman-batut — APPROVED** [review]
LGTM

**Pull request merged**
