### PR TITLE
Test/basic unit tests

### PR DESCRIPTION
**Pull request by Tristan-C789**
### Basic WelcomeScreens tests
A 5-tests suite for WelcomeScreens to check test-coverage and basic test structure.

### CODE REVIEW

**Review by Roman-batut — COMMENTED** [review]
### Comment:
Add comments above tests as good practice. It may be explicit by names but for longer test files it'll be easier this way.

### Example:
// Test display of title in Welcome_Intro
test('welcome_intro correctly displays title', () => {...}

**Review by marcjadaa — COMMENTED** [review]
LGTM

**Review by marcjadaa — COMMENTED** [review]
LGTM

**Comment by Tristan-C789** [comment]
> ### Comment:
> Add comments above tests as good practice. It may be explicit by names but for longer test files it'll be easier this way.
> 
> ### Example:
> // Test display of title in Welcome_Intro test('welcome_intro correctly displays title', () => {...}

I believe this was made clearer in the modularisation I did. what do you think ?

**Review by Roman-batut — APPROVED** [review]
LGTM

**Review by margdsq — COMMENTED** [review]
LGTM

**Pull request merged**
